name: CI

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test (Java 21)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 #v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Set gradlew as executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew --no-daemon clean build

      - name: Upload unit test results (XML)
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results-xml
          path: build/test-results/test
          if-no-files-found: warn

      - name: Upload unit test report (HTML)
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-report-html
          path: build/reports/tests/test
          if-no-files-found: warn
